### ISSUE TITLE
[분석] 상품 데이터 추가 분석

### ISSUE THREAD

**Issue by nahyun-song** [dataitgirls6/nae_house#13]
- 2차 기술 피드백 이후 추가적인 분석을 진행합니다.

**Comment by nahyun-song** [comment]
<img width="475" alt="스크린샷 2022-12-07 15 40 11" src="https://user-images.githubusercontent.com/75622751/206107062-d8e37d47-5d2d-415d-ae0b-ca5feef7c417.png">
인기랭캥, 판매랭킹 데이터를 추가하여 분석해봤는데, 유의미한 결과를 얻지 못햇습니다 ㅠㅠ
우리가 가지고 있는 수치형 데이터로 분위기를 예측하는 건 어려울 것 같아요. 
리뷰데이터 크롤링이 시급합니다......😢

**Comment by dallaemin** [comment]
앞서 상품명에서 분위기가 드러나는 단어가 있는지 확인해보았습니다. 예를 들어 '한국&아시아' 분위기에 '이케아'(브랜드) 상품을 보았는데, '우드', '베크', '~나무'와 같은 단어는 나오더라구요. 그런데 한 분위기에 특정된 단어는 아니기 때문에 상품명으로는 분위기를 분류하는 것은 어렵다고 판단내렸습니다. 앞으로 태깅되지 않은 상품은 리뷰를 기준으로 분위기를 결정해야할 것 같아요. 정리하면 아래와 같습니다!

[분위기 기준]
- 집들이 글에 태깅된 상품 : 집들이 글 제목 
- 집들이 글에 태깅되지 않은 상품 : 상품의 리뷰 

앞으로 '집들이 글에 태깅되지 않은 상품'의 분위기 결정에 집중하면 될 것 같아요.
