### ISSUE TITLE
[수집] 상품 리뷰 데이터 스크래핑

### ISSUE THREAD

**Issue by nahyun-song** [dataitgirls6/nae_house#15]
- 감성 분석, 텍스트 분석을 위한 리뷰데이터를 수집합니다.
- 수집할 feature : `상품url`, `상품명`, `분위기`, `별점`, `리뷰`

```
 김민지 [0:229]
 박유정 [229:458]
 송나현 [458:687]
 이소현 [687:916]
 최수연 [916:1145]
```

**본인 파트 완료시 댓글 남겨주세요!**
관련 오류는 #16 에 남겨주시면 됩니다 ☺️

**Comment by dallaemin** [comment]
[0:229] 완료했습니다.

**Comment by nahyun-song** [comment]
[458:687] 완료했습니다!

**Comment by yujeong0121** [comment]
[229:458] 완료했습니다.

**Comment by sohyunizi** [comment]
[687:916] 완료했습니다!

**Comment by csuyeon728** [comment]
[916:1145] 완료했습니다~

**Comment by nahyun-song** [comment]
데이터 수집 완료되어 이슈 닫습니다.
