### ISSUE TITLE
[분석] 상품 리뷰 데이터 개인 분석

### ISSUE THREAD

**Issue by nahyun-song** [dataitgirls6/nae_house#17]
- 상품 리뷰 데이터 분석을 진행합니다.
- 텍스트 분석, 리뷰 감성 분석 등

**Comment by nahyun-song** [comment]
긍정비율과 다른 수치형 데이터를 가지고 회귀분석을 진행했습니다.

<img width="445" alt="스크린샷 2022-12-14 18 54 15" src="https://user-images.githubusercontent.com/75622751/207563789-33932cec-2c78-4d7f-a2d4-bd04971e0722.png">

역시나 유의미한 결과는 없었는데요, 긍정 비율과 별점이 높은 상관관계를 가지고 있더라구요.
이걸 활용해보면 좋을 것 같은데....
통계수업시간에 봤던 예제 중에서 맛집리뷰 내용은 부정적이지만 별점은 높았던 사례나 그 반대 사례를 제시해서
긍정비율과 별점의 상관관계는 높지만, 별점을 믿을 수 없다 = 별점만 가지고는 긍정적인 리뷰라는 것을 보장할 수 없다
는 걸 주장해보면 어떨까요??

**Comment by nahyun-song** [comment]
제목에서 추출한 키워드를 상품 데이터에 적용해봤는데, 분위기가 잘 분류되는 것 같아요!
집들이 데이터에 태깅되지 않은 상품은 이 방식으로 분위기를 분류하는 걸로 합시다 ☺️

**Comment by dallaemin** [comment]
네 좋습니다! 리뷰 데이터를 활용해서 상품의 긍/부정 비율을 상세하게 살펴보는 과정이 필요할 것 같아요. 그럼 상품 추천 기준이 더 명확해 질 것 같습니다. 그리고 앞으로 태깅되지 않은 상품들 또한 리뷰 데이터로 분위기 분류를 하는걸로 합시다! 
의미있는 인사이트를 제공할 수 있을 것 같아 매우 기대됩니다!

[리뷰 데이터 활용]
- 상품의 긍정 비율 -> 상품 추천 기준 제공
- 상품의 분위기 부여 -> 상품 분위기 기준 설정

**Comment by sohyunizi** [comment]
대체적으로 정비례하네요. R-squared값이 높은 것들도 거의 비슷한것들이니 그 중에서 잘 활용할 수 있는 것들을 골라 봐야겠어요. 텍스트리뷰와 별점이 상반된 케이스를 수집하는 아이디어 정말 좋네요! 집들이 속 키워드(분위기)와 리뷰 속에 나오는 키워드와 비슷한 키워드를 찾아 태깅이 안된 제품을 스타일 별로 분류해보는 것도 좋을 것 같습니다.

**Comment by csuyeon728** [comment]
별점은 사용자마다 주관적인 면이 있는 것 같아서 별점과 리뷰와 반대되는 사례를 들어서 주장해보는 아이디어 좋은 것 같아요~  태깅되지 않은 상품의 리뷰 데이터를 분석해보면 집들이 컨텐츠 제목의 키워드와도 특색 있는 연관성이 있을 것 같아요. 더불어 태깅되지 않은 상품별 분위기를 정의해주는 건 집들이에 태깅되지 않은 상품의 판매량 증가와 새로운 컨텐츠 증가까지 기대 효과로 생각해봅니다.

**Comment by nahyun-song** [comment]
그리고 저번 피드백 때 살짝 언급하셨던, 연관분석을 진행해보는 건 어떨까요??
연관분석을 바탕으로 마지막 조합상품을 제시하는 거요!

**Comment by yujeong0121** [comment]
저는 연관분석 진행하는 거 찬성이요! 집들이 선물은 아니지만 친구 생일 선물을 고를 때 잠옷을 골랐더니 이미 여러 개 받았다고 다른 거 사달라고 하더군요. 새로운 제품군을 다시 고르기 어려워서 수면 관련 다른 제품을 선물했던 경험이 있어요. 그런 경우를 대비해서 연관 있는 상품을 추천해주는 방향으로 풀어보면 좋을 것 같습니다.

**Comment by nahyun-song** [comment]
모두들 의견 감사합니다!
그럼 저는 연관분석 관련해서 같은 사진에 태깅된 상품을 스크래핑하는 코드를 짜볼게요!
