### ISSUE TITLE
[수집] 집들이에 태깅된 상품 데이터 스크래핑

### ISSUE THREAD

**Issue by nahyun-song** [dataitgirls6/nae_house#7]
- 집들이에 태깅된 상품을 스크래핑하는 코드입니다.
- 지난 번 집들이 데이터 수집시 중간에 끊기는 경우 저장이 되지 않는 문제를 개선하였습니다.
- 집들이 데이터 수집하는 방식과 동일하게 본인이 맡은 부분을 스크래핑 해주시면 됩니다.
- 스크래핑 완료시 드라이브에 업로드 한 후 코멘트 남겨주세요!

**본인이 맡은부분을 start와 end에 넣어주세요.**

`김민지`  [11300:45300]
`김예원`  [45300:79300]
`박유정`  [79300:113300]
`이소현`  [113300:147300]
`이지혜`  [147300:181300]
`최수연`  [181300:215300]
`송나현`  [:11300], [215300:]

**Comment by kimeong** [comment]
[45300:79300] 완료했습니다!

**Comment by nahyun-song** [comment]
[:11300], [215300:] 완료했습니다.

**Comment by csuyeon728** [comment]
[181300:215300] 완료했습니다~!

**Comment by dallaemin** [comment]
[11300:45300] 완료했습니다.

**Comment by sohyunizi** [comment]
[113300:147300] 완료했습니다!

**Comment by yujeong0121** [comment]
[79300:113300] 완료했습니다!

**Comment by JuriaLee** [comment]
[147300:181300] 완료했습니다!

**Comment by nahyun-song** [comment]
스크래핑 완료되어 이슈 닫습니다!
