### ISSUE TITLE
[오류] 집들이에 태깅된 상품 데이터 스크래핑 오류

### ISSUE THREAD

**Issue by nahyun-song** [dataitgirls6/nae_house#8]
- 집들이에 태깅된 상품 스크래핑 오류를 남겨주세요!

**Comment by JuriaLee** [comment]
저 코드 마지막 파트에서 Keyerror:'url' 이라는 오류가 나는데 어떤 문제일까요ㅠㅠㅠㅠ?

**Comment by JuriaLee** [comment]
저 64900-65000, 159900-160000 여기 100개씩 돌려야하는데 나현님이 알려주신 방법대로 해도 계속 오류가 나요^_ㅜ(파일 저장 안되고 꺼짐) 혹시 다른 방법 있을까요?

**Comment by nahyun-song** [comment]
> 저 64900-65000, 159900-160000 여기 100개씩 돌려야하는데 나현님이 알려주신 방법대로 해도 계속 오류가 나요^_ㅜ(파일 저장 안되고 꺼짐) 혹시 다른 방법 있을까요?

이 부분은 그럼 제가 한 번 돌려볼게요!

**Comment by kimeong** [comment]
혹시.. 코랩에서… 갑자기 chromedriver unexpectedly exited. Status code was: -6 < 이런 오류 나셨던 분 있나요…. ㅠㅠ 주피터에서는 안났는데 갑자기 나서… 서치해도 안나오네요

**Comment by sohyunizi** [comment]
잘돌아가다가 특정상품에서 오류가 나는데 문제 없던 path가 문제라고 뜨네요.. 100개 넘어가기 전에 문제가 생겨서 그런가 되는데까지 파일이 안생깁니다. 원랜 [113300:147300]인데 [113400:147300]부터 돌리고 있습니다. 일단은 잘 돌아가고 있어요!

**Comment by sohyunizi** [comment]
path를 처음에 정의를 안하고 했네요ㅠㅜ 원인 찾았습니다~!  해결 완!

**Comment by dallaemin** [comment]
저 3000개쯤 진행했는데 계속해서 timeout exception이 발생하네요.. 어떻게 해야할까요?

**Comment by nahyun-song** [comment]
> 

주피터랑 코랩이랑 크롬 드라이버가 조금 다르더라구요! 주피터랑 코랩이랑 코드 다르게 올렸으니 참고해주세요! ☺️

**Comment by nahyun-song** [comment]
> 혹시.. 코랩에서… 갑자기 chromedriver unexpectedly exited. Status code was: -6 < 이런 오류 나셨던 분 있나요…. ㅠㅠ 주피터에서는 안났는데 갑자기 나서… 서치해도 안나오네요

주피터랑 코랩이랑 크롬 드라이버가 조금 다르더라구요! 주피터랑 코랩이랑 코드 다르게 올렸으니 참고해주세요! ☺️

**Comment by nahyun-song** [comment]
> 



> 저 3000개쯤 진행했는데 계속해서 timeout exception이 발생하네요.. 어떻게 해야할까요?

가끔 로딩이 미친듯이 안되면 타임아웃으로 닫히더라구요 😢
start를 14400로 변경하고 런타임 > 다시시작 및 모두실행
해보시고 안되면 넘기셔도 됩니다^_^

**Comment by nahyun-song** [comment]
모든 오류 해결되어 이슈 닫겠습니다!
